server.port=80

logging.level.org.springframework.web=info
logging.level.com.example.springedu=debug
logging.level.thymeleaf.exam=trace

logging.level.com.example.springedu.controller=info


## JPA
spring.datasource.url=jdbc:oracle:thin:@15.164.225.1:1521:xe
spring.datasource.username=memo
spring.datasource.password=memo
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# timezone Error
spring.datasource.hikari.data-source-properties.oracle.jdbc.timezoneAsRegion=false



